development: &development
  HOST: 'http://localhost:3000'
test:
  <<: *development

staging:
  <<: *development
  HOST: 'http://redespiertatubarrio.imjuventud.gob.mx'
production:
  <<: *development
  HOST: 'http://redespiertatubarrio.imjuventud.gob.mx'