#encoding: utf-8
User.create(username: 'Admin', email: 'test@imjuve.com', password: '12345678', password_confirmation: '12345678', is_admin: true)
UserType.create(name: 'Admin')
UserType.create(name: 'Capacitador')
UserType.create(name: 'Encuestador')
UserType.create(name: 'Usuario')
servicios = ParentCategory.create(:name => "Servicios Públicos")
familias = ParentCategory.create(:name => "Familias")
otros = ParentCategory.create(:name => "Otros")
Category.create(:name => "Agua potable y saneamiento", :parent_category_id => servicios.id)
Category.create(:name => "Alcantarillado", :parent_category_id => servicios.id)
Category.create(:name => "Residuos Sólidos", :parent_category_id => servicios.id)
Category.create(:name => "Calles, vialidades y accesos", :parent_category_id => servicios.id)
Category.create(:name => "Alumbrado público", :parent_category_id => servicios.id)
Category.create(:name => "Energía eléctrica", :parent_category_id => servicios.id)
Category.create(:name => "Espacios públicos, parques y jardines (infraestructura)", :parent_category_id => servicios.id)
Category.create(:name => "Seguridad Pública y tránsito", :parent_category_id => servicios.id)
Category.create(:name => "Asistencia médica", :parent_category_id => servicios.id)
Category.create(:name => "Infraestructura educativa", :parent_category_id => servicios.id)
Category.create(:name => "Rezago educativo", :parent_category_id => servicios.id)
Category.create(:name => "Integración familiar", :parent_category_id => familias.id)
Category.create(:name => "Violencia intrafamiliar", :parent_category_id => familias.id)
Category.create(:name => "Planificación familiar", :parent_category_id => familias.id)
Category.create(:name => "Equidad de género", :parent_category_id => familias.id)
Category.create(:name => "Empleo y planeación socioeconómica", :parent_category_id => otros.id)
Category.create(:name => "Vivienda", :parent_category_id => otros.id)
Category.create(:name => "Salud, higiene, prevención y combate a las adicciones", :parent_category_id => otros.id)
Category.create(:name => "Medio ambiente", :parent_category_id => otros.id)
Category.create(:name => "Alimentación y nutrición", :parent_category_id => otros.id)
Category.create(:name => "Participación ciudadana y vecinal", :parent_category_id => otros.id)
Category.create(:name => "Deporte y atención a la juventud con programas sociales, culturales y recreativos", :parent_category_id => otros.id)
Category.create(:name => "Transferencia o desarrollo de tecnología", :parent_category_id => otros.id)